### ISSUE TITLE
Aggiornamenti dati

### ISSUE THREAD

**Issue by Spazio2001** [gabrielepinto/dati-sezioni-elettorali#1]
Buongiorno,
complimenti per l'ottimo lavoro. Per il 31/05/2022 era segnato un aggiornamento per Bologna e Palermo, ma non è avvenuto. Quando avverrà?

**Comment by gabrielepinto** [comment]
buongiorno @Spazio2001 ,
ho caricato gli shapefile nella cartella https://github.com/gabrielepinto/dati-sezioni-elettorali/tree/main/shapefiles_sezioni_elettorali
 spero entro mercoledi di caricare anche i risultati elettorali.
